layoutdir = "themes/academic-group/layouts"
publishdir = "public"
static = "/static"
builddrafts = false
# Replace this with your website URL
baseurl = "http://rapeseed.zju.edu.cn/"
canonifyurls = true
theme = "academic-group"
title = "Li-Xi Jiang lab"
math = true
copyright = "&copy; JiangLX Lab, 2020 "
enableRobotsTXT = true

[taxonomies]
category = "categories"
tag = "tags"


[params]
  description = "Website of research group"
  author = "Li-Xi Jiang"
  email = "jianglx@zju.edu.cn"
  phone = "0571-88982905"
  address = '<a href="https://www.google.nl/maps/place/%E6%B5%99%E6%B1%9F%E5%A4%A7%E5%AD%A6%E5%86%9C%E4%B8%9A%E4%B8%8E%E7%94%9F%E7%89%A9%E6%8A%80%E6%9C%AF%E5%AD%A6%E9%99%A2/@30.2723396,120.1930973,17z/data=!3m1!4b1!4m5!3m4!1s0x344c9db0439fdf9b:0xdae986ed589acbe4!8m2!3d30.272335!4d120.195286">Building A Room 367, Zhejiang University (ZJG Campus), Hangzhou, 310058, China</a>'
  slogan = "Laboratory of Plant Molecular Physiology"
  slogan_text = "Brassica, Oil, Genome, Heterosis, Biology"

  [params.logo]
    image = "img/zjulogo.svg"
    link = "http://www.zju.edu.cn/"

  [[params.navbar_hierarchy]]
    name = "Li-Xi Jiang Lab"
    link = "/"
    position = 1

  [[params.slogan_columns]]
    title = ""
    text = ""
 #   link = "/approach"
 #   link_text = "Read more"
 #   weight = 1
 #   weight = 3
  
  [[params.slogan_columns]]
    title = ""
    text =  "Li-Xi jiang lab studies Molecular mechansim of oil-yield formation in oilseed rape (Brassica napus) and the effect of seed dormancy degree on oil content of rapeseed and the underlying molecular mechanisms"
    link = "/research"
    link_text = "Read more"
    weight = 2
  
 # [[params.slogan_columns]]
 #   title = "Mission"
 #   text = "Per peterem ex, Eurystheus videt maeonis, Paeonis uritur. Dextera [legem](http://nubibus.net/qualisardeat), contigerat optabile undis bene: abis sperato. Instrumenta arma, subiectas generis non ipsa patres quia magna Messeneque lacrimaeque torva. Aequo crescunt inrequieta feras, diu illa est occupat aequoribus hunc Elpenora tollens vult robore. Finiat priora vulnere nec Nelei fit quae totidemque intibaque iter longo."
 #   link = "/mission"
 #   link_text = "Read more"
 #   weight = 2



  # Selected Publications section.
  [params.publications_selected]
    detailed_list = true
    title = "Selected Publications"
    subtitle = ""

  # Publications section.
  # Section will only be displayed if there are publications in `content/publication/`.
  [params.publications]
    count = 5
    detailed_list = false
    title = "Publications"
    subtitle = ""
    str_all = "More Publications"

  # Posts section.
  # Section will only be displayed if there are posts in `content/post/`.
  [params.posts]
    count = 2
    title = "Blog"
    subtitle = ""
    str_all = "More Posts"
    str_read_more = "Read more"

  # Members section.
  [params.members]
    count = 8

  # Projects section.
  # Section will only be displayed if there are projects in `content/project/`.
  [params.projects]
    title = "Projects"
    subtitle = ""
    count = 5
    str_all = "More Projects"
  
  # Vacancies section
  # Section will only be displayed if there are valid classes in `content/class`
#  [params.classes]
#    title = "Teaching"
#    subtitle = ""
#    count = 3
#    str_all = "More Classes"
    
  # Contact section.
  [params.contact]
    enable = true
    title = "Contact"
    subtitle = ""
    autolink = true  # Automatically link email and phone?

  # Navigation Links
  #   The weight parameter defines the order that the links will appear in.

  [[menu.main]]
      name = "Home"
      url = "/#home"
      weight = 1


  [[menu.main]]
      name = "Publications"
      url = "/#publications"
      weight = 2

  [[menu.main]]
      name = "Projects"
      url = "/#projects"
      weight = 3

  [[menu.main]]
      name = "Cloud"
      weight = 4
      identifier = "cloud"
  [[menu.main]]
    name = "Bna_GWAS"
    url = "/cloud/gwas"
    parent = "cloud"
    weight = 2

  [[menu.main]]
      name = "Members"
      url = "/#members"
      weight = 4

  [[menu.main]]
      name = "Teaching"
      url = "/class/class"
      weight = 5

  [[menu.main]]
      name = "Blog"
      url = "/#posts"
      weight = 6


  [[menu.main]]
      name = "Contact"
      url = "#contact"
      weight = 7
      

